services:
  mailglove:
    build:
      context: .
      dockerfile: Dockerfile
    image: mailglove
    container_name: mailglove
    environment:
      - DOMAIN=radarevents.wiselynx.com
      - URL=https://eofdjz65tg2v2vt.m.pipedream.net
    ports:
      - "25:25"
